{
 "title": "Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Network latency",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "network_latency_seconds{status=\"success\"}"
    }
   ]
  },
  {
   "title": "App response time",
   "type": "timeseries",
   "description": "Average response time quantiles across instances",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "avg without (instance) (http_response_time_seconds{path=\"/load\"})"
    }
   ]
  },
  {
   "title": "Combined latency",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(avg without(instance) (http_response_time_seconds{path=\"/load\"})) + on(quantile, host) network_latency_seconds"
    }
   ]
  }
 ]
}