apiVersion: v1
kind: Namespace
metadata:
  name: pi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-deployment
  namespace: pi
  labels:
    app: go-server
spec:
  replicas: 6
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
      - name: go-server
        image: ghcr.io/agmcc/csc8499/go-server
        resources:
          limits:
            cpu: "2"
            memory: "200M"
        env:
          - name: HOST
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: DIFFICULTY
            value: "0"
      imagePullSecrets:
        - name: ghcr
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - arm
---
apiVersion: v1
kind: Service
metadata:
  name: pi-service
  namespace: pi
spec:
  type: NodePort
  selector:
    app: go-server
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30000
