apiVersion: v1
kind: Namespace
metadata:
  name: pi
---
apiVersion: v1
kind: Pod
metadata:
  name: pi-pod
  namespace: pi
  labels:
    app: go-server
spec:
  containers:
  - name: go-server
    image: ghcr.io/agmcc/csc8499/go-server
    resources:
      limits:
        cpu: "1"
        memory: "200M"
    env:
      - name: HOST
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: DIFFICULTY
        value: "1"
  imagePullSecrets:
    - name: ghcr
  nodeSelector:
    kubernetes.io/hostname: pilab-01
---
apiVersion: v1
kind: Service
metadata:
  name: pi-service
  namespace: pi
spec:
  type: NodePort
  selector:
    app: go-server
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30000
