apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-deployment
  labels:
    app: go-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      # Use custom scheduler
      schedulerName: iot-scheduler
      containers:
        - name: go-server
          image: ghcr.io/agmcc/csc8499/go-server
          resources:
            limits:
              cpu: "1"
              memory: "200M"
          env:
            - name: HOST
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: DIFFICULTY
              value: "1"
      imagePullSecrets:
        - name: ghcr
      # Limit 2 pods per node
      topologySpreadConstraints:
        - maxSkew: 2
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: go-server
