apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: seed-daemon-set
  labels:
    app: go-server
spec:
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: go-server
          image: ghcr.io/agmcc/csc8499/go-server
          resources:
            limits:
              cpu: "1"
              memory: "200M"
          env:
            - name: HOST
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: DIFFICULTY
              value: "1"
      imagePullSecrets:
        - name: ghcr
