apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
  namespace: monitoring
data:
  prometheus.yml: |-
    global:
      scrape_interval: 10s

    rule_files:
      - prometheus_rules.yml

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__

  prometheus_rules.yml: |-
    groups:
      - name: metrics
        rules:
        - record: network_latency
          expr: ceil(avg without (instance) (network_latency_seconds{status='success', quantile='0.5'}) * 1000)
        - record: response_time
          expr: ceil(avg without(instance, kubernetes_pod_name) (http_response_time_seconds{path='/load', quantile='0.5'}) * 1000)
