{
 "title": "Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Combined latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(avg without (instance) (network_latency_seconds{status=\"success\", quantile=\"0.5\"}) * 1000) + on(host) (avg without(instance) (http_response_time_seconds{path=\"/load\", quantile=\"0.5\"}) * 1000)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Network latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "\navg without (instance) (network_latency_seconds{status=\"success\", quantile=\"0.5\"}) * 1000",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "App response time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "avg without(instance, kubernetes_pod_name) (http_response_time_seconds{path=\"/load\", quantile=\"0.5\"}) * 1000",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}