apiVersion: v1
kind: Pod
metadata:
  name: custom-scheduled-pod
  labels:
      app: go-server
spec:
  schedulerName: iot-scheduler
  containers:
  - name: go-server
    image: ghcr.io/agmcc/csc8499/go-server
    resources:
      limits:
        cpu: "2"
        memory: "200M"
    env:
      - name: HOST
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: DIFFICULTY
        value: "0"
  imagePullSecrets:
    - name: ghcr
  tolerations:
  # Allow on master
  - key: node-role.kubernetes.io/master
    value: "true"
    effect: NoSchedule
